import React from 'react'
import { TemplateProj } from '../TemplateProj'
import { TrainingSimRenders, TrainingSimProgress } from '/src/constants/gallery.js'

const TrainingSimData = {
  title: 'Training Simulator',
  role: <span><em>Team</em> - Technical Artist</span>,
  icons: [{ src: './assets/AboutIcons/Technologies/Unreal.png', alt: 'Unreal' }, { src: './assets/AboutIcons/Technologies/Blender.png', alt: 'Blender' }, { src: './assets/AboutIcons/Technologies/AdobeAudition.png', alt: 'Adobe Audition' }, { src: './assets/AboutIcons/Technologies/AdobePhotoshop.png', alt: 'Adobe Photoshop' }, { src: './assets/AboutIcons/Languages/C++.png', alt: 'C++' }],
  splashSrc: './assets/gallery/TrainingSim/TrainingSimSplash.png',
  synopsis: <span>This VR docking training simulator was constructed during my time at Brunswick’s BI Design Lab. It was a virtual reality game designed with the intent to supplement boat training for Freedom Boat Club (FBC) members. By simulating the experience at a physical FBC location, our program helped people feel more confident docking <em>before</em> even having stepped on a boat!</span>,
  tasks: <span>I was primarily tasked with building out our program’s immersive environment. I modelled out a one-to-one replica of Brunswick’s Streeterville location in Chicago, Illinois. This also extended to modelling, texturing, and rigging smaller actors scattered across the scene, like the boats and seagulls. My role also included full control over sound design and the clearance to program a couple of UI screens and instructive mini-games.</span>,
  renderImages: TrainingSimRenders,
  progressImages: TrainingSimProgress,
  challenges: [
    { title: 'Minigames', body: <span>
      The simulator included an “Assisted Mode,” which provided players with more guidance in the form of instructive mini-games. I was in charge of building two of our final three games. 

      <br></br>
      <br></br>

      <ol className="list-decimal pl-5 space-y-1">
        <li><b>Engine Checking: </b>A game designed to encourage players to regularly check their engine. When boating, your engine acts as a good indicator of direction. You’d need to check it regularly to ensure you know where your boat is tilted. </li>

        <li><b>Throttle Minigame: </b> A game designed to accustom users to using throttle pressure. In real life, a small difference in throttle location can be a difference between 60 RPM and 100 RPM!</li>
      </ol>

      <br></br>
      <br></br>

      While coding out these games, I consistently checked in with my team and our users. VR has many limitations whose solutions aren’t necessarily transferable from traditional games. How should you grab your user’s attention when you’re not sure where they’re looking? Our team held several user tests and user interviews with boating teachers, as well, to ensure we were prioritizing the right features. And these elements had to be conveyed in a clear, intuitive way. 
      
    </span> },
    { title: 'Modelling', body: <span>
      The training simulator’s environment was built in Blender and meant to replicate FBC’s Streeterville dock in Chicago, Illinois. Since it was essential that users build a sense of familiarity with the real location’s layout and landmarks, I was incentivised to make the model as accurate as possible. And this was done while keeping in mind that, since this was to be a real-time simulation, all assets had to be optimized. 

      <br></br>
      <br></br>

      Our original prototype was made up of a ripped Google Maps model of the surrounding area. But this model was ultimately unusable because of how bloated and messy the resulting mesh was. For a real-time simulation, it was less than ideal. So, we instead used the Google Maps mesh as a reference for the buildings’ general silhouettes and shapes. In the game itself, the majority of the buildings will be too distant to distinguish detailing anyway. In this case, it’s most important to get the shape and texture of the building correct.

      <br></br>
      <br></br>

      Adding realistic textures to our environmental buildings was more difficult than you might expect. By the nature of our original prototype, it was impossible to separate one structure’s mesh from the mesh as a whole. This made baking and transferring textures from the high-poly model to the low-poly model very difficult. And to make matters worse, the texture maps generated by the Google Maps model were scattered across buildings. In other words, one skyscraper’s textures might be inconsistently split across ten different images. So, in order to keep our model’s real-to-life textures, I took a screenshot of each building from all angles and compiled them into a single image. Then, I used Blender’s texture paint option to stamp each perspective onto our simplified model.

      <br></br>
      <br></br>

      When building out the props for the game, such as the player’s main boat pawn, I learned the necessity of building both a physics mesh and a visual mesh. And doing so often included simplifying massive meshes down from millions of polygons to only a couple hundred.
      
      <br></br>
      <br></br>

      I had three different approaches to simplifying any given model.

      <br></br>
      <br></br>

      <ol className="list-decimal pl-5 space-y-1">
        <li><b>Manual Retopology: </b>This covers the painstaking process of covering a high-poly model with new topology. It’s a solid go-to if you want the most control over the final product, but it can take a long time. If you’re on any kind of time crunch, it’s not preferable.</li>

        <li><b>Decimate Modifier: </b>Blender has a built-in modifier for reducing a model’s polygon count. It’s convenient and quick, but it doesn’t always result in the cleanest topology. Since it’s automated for you, you have little control over the resulting polygon count, details, and shape.</li>

        <li><b>Shrinkwrap Modifier:</b>Blender also has another modifier, which, while not traditionally used for retopology efforts, can come in handy. The shrinkwrap modifier lets one model envelop or “shrink” onto another. Meaning that if you create a general block-out shape with a desired number of vertices and shrinkwrap it to your high-poly mesh, you get an all-around accurate recreation.</li>
      </ol>

      <br></br>
      <br></br>

      Often when simplifying a model using Blender’s automated methods, it’s easier to add details <em>after</em> simplifying instead of struggling to maintain detail throughout the retopological process.
      
    </span> },
    { title: 'Audio', body: <span>

      I was in charge of all the audio elements in our final product. This means cutting, mixing, and mastering background music and other sound effects. 

      <br></br>
      <br></br>

      <ol className="list-decimal pl-5 space-y-1">
        <li><b>Unreal MetaSounds: </b>Unreal 5 began a marketed shift from Sound Cues to their new system, MetaSounds, which closely resembles a blueprint scripting system. I learned to use MetaSounds to create dynamic, custom feedback for each player by building an algorithm that adjusts sound cues based on a player’s in-game velocity, and one that plays a sound based on the direction of the player’s real-life throttle controller.</li>
        <li><b>Mixing Audio: </b>There was one issue I encountered with a provided audio clip. The sound was a snippet of some boat’s engine, which could, in theory, be played indefinitely throughout the game. But the audio didn’t loop perfectly. There was always a very noticeable pop. And, while I could loop the clip with the MegaSounds system, that didn’t fix the base issue with the audio itself. Usually, with looping, I crop the audio where both the beginning and end are at a zero-crossing. But since this sound used two audio tracks, one for the left ear and one for the right, it was nearly impossible to find a moment when both tracks crossed zero. Furthermore, After Effects’ built-in looping tools never accounted for infinite loops. So instead, I decided to instigate a dual-track zero-crossing myself. And, as anyone with any audio experience may know, but I, as a novice, was completely unaware of, this can be achieved by adding a small fade to both ends of the audio.</li>
      </ol>

      
    </span> },
  ],
  insights: <span>

    I’m immensely proud of my work for this project, even though I think I can do better today. It helped me learn how to model, code, and design on a quick, professional timeline. I needed to be efficient and clever with what I chose to spend my time on, and that meant being realistic. Often perfectionism gets in the way of success, and that was especially evident in my time working on the training simulator. If I spent hours on every little detail, nothing would have gotten done at all. 
      
    </span>
}

export const TrainingSim = () => <TemplateProj {...TrainingSimData} />