/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dunes_v02.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Dunes(props) {
  const { nodes, materials } = useGLTF('src/assets/models/Dunes_v02.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Landscape.geometry} material={materials['Sand Dunes']} scale={2.408} />
    </group>
  )
}

useGLTF.preload('src/assets/models/Dunes_v02.glb')
